"""Spec -> a deterministic Python module. The only "code generation" A2 does.

**Translation, not invention** (App-Flow §4.2). A `StrategySpec` already *is*
a complete, executable description of a strategy — `compile_spec` proved that
in Stage 2. So rendering it into `strategies/<uid>/strategy.py` is a
tree-walk with one shape, not a creative act: embed the spec's canonical JSON,
reconstruct it, compile it. Two specs that mean the same thing render to
byte-identical modules; nothing here depends on wording, node ids, or
declaration order — the same properties `spec_hash` already guarantees.

**Why this is what makes A2 safe rather than merely convenient.** A strategy
whose code was free-form Python would need its own look-ahead review every
time; a strategy whose code is `compile_spec(SPEC)` inherits Stage 2's
registry-wide causality proof and Stage 3's engine unconditionally. The one
thing this module must never get wrong is the round-trip: `render_module`
followed by reconstructing the embedded JSON must reproduce a spec whose
`spec_hash()` matches the original bit for bit (`checks.py` verifies this on
every render, not just in tests).
"""
from __future__ import annotations

import json
from dataclasses import dataclass

from ..hashing import content_hash
from ..operators.spec import StrategySpec

__all__ = ["RenderedModule", "code_path_for", "render_module"]

_TEMPLATE = '''"""Generated by aqrl.agents.render — do not edit by hand.

Strategy: {strategy_uid}
spec_hash: {spec_hash}
Rendered from strategy_specs version {spec_version}.

Composed entirely from the operator library (TRD §11); this module invents no
logic of its own. Signals are computed from data at or before each bar — the
entry lag is applied centrally by the evaluation engine, never here.
"""
from __future__ import annotations

import json

from aqrl.operators import StrategySpec, compile_spec

SPEC_HASH = {spec_hash!r}

_SPEC_JSON = r"""{spec_json}"""

SPEC = StrategySpec(**json.loads(_SPEC_JSON))

generate_signals = compile_spec(SPEC).to_signal_fn()
'''


@dataclass(frozen=True)
class RenderedModule:
    source: str
    code_hash: str


def code_path_for(strategy_uid: str) -> str:
    """`strategies/<strategy_uid>/strategy.py` (Backend-Schema §4).

    Each strategy at its own path so many strategies can later merge into one
    `deploy/*` branch conflict-free (TRD §5.2) — a property this function
    exists to make impossible to get wrong at any call site.
    """
    return f"strategies/{strategy_uid}/strategy.py"


def render_module(spec: StrategySpec, *, strategy_uid: str, spec_version: int) -> RenderedModule:
    """Render `spec` into the module `evaluate.py`'s P0 scanner will read.

    The embedded JSON is `spec.model_dump(mode="json")` — round-tripping it
    through `StrategySpec(**json.loads(...))` must reproduce a spec whose
    `spec_hash()` equals `spec.spec_hash()`; `checks.py` asserts this every
    time, so a template bug here is caught before a commit ever happens.
    """
    payload = spec.model_dump(mode="json")
    spec_json = json.dumps(payload, indent=2, sort_keys=True)
    source = _TEMPLATE.format(
        strategy_uid=strategy_uid,
        spec_version=spec_version,
        spec_hash=spec.spec_hash(),
        spec_json=spec_json,
    )
    return RenderedModule(source=source, code_hash=content_hash(source))
