"""SQLite connections and SQL-dialect handling.

TRD §20 and Backend-Schema §16 impose one constraint that shapes this module:
**no SQLite-specific SQL**, because Stage 13 must swap SQLite for PostgreSQL as
a *backend swap, not a rewrite*. Two things follow.

First, the handful of genuinely dialect-specific constructs live behind
substitution tokens resolved here, and nowhere else:

    {{PK}}    autoincrementing surrogate primary key
    {{JSON}}  JSON document column
    {{BOOL}}  boolean column

Second, **no SQL-level timestamp defaults.** `DEFAULT (datetime('now'))` is
SQLite-only, so timestamps are stamped in Python by the repository layer
(`aqrl.db.repositories.base.utcnow_iso`). Doing it in one place also means every
row in the database agrees on ISO-8601 UTC, which Backend-Schema §0 requires.
"""
from __future__ import annotations

import sqlite3
from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path
from typing import Literal

Dialect = Literal["sqlite", "postgresql"]

DIALECT_TOKENS: dict[Dialect, dict[str, str]] = {
    "sqlite": {
        "PK": "INTEGER PRIMARY KEY",
        "JSON": "TEXT",
        "BOOL": "INTEGER",
    },
    "postgresql": {
        "PK": "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "JSON": "JSONB",
        "BOOL": "BOOLEAN",
    },
}


def render_sql(sql: str, dialect: Dialect = "sqlite") -> str:
    """Resolve `{{TOKEN}}` placeholders for the target dialect."""
    try:
        tokens = DIALECT_TOKENS[dialect]
    except KeyError:
        raise ValueError(f"unknown dialect: {dialect!r}") from None
    for name, replacement in tokens.items():
        sql = sql.replace("{{" + name + "}}", replacement)
    if "{{" in sql:
        start = sql.index("{{")
        raise ValueError(f"unresolved dialect token near: {sql[start:start + 40]!r}")
    return sql


def split_statements(sql: str) -> list[str]:
    """Split a SQL script into statements.

    Executing statements one at a time (rather than `executescript`) keeps the
    migration inside a transaction we control and makes a failure point at the
    statement that broke. Quote- and comment-aware so a `;` inside a string
    literal or a trailing comment does not split a statement in half.
    """
    statements: list[str] = []
    current: list[str] = []
    in_string = in_line_comment = in_block_comment = False
    index = 0

    while index < len(sql):
        char = sql[index]
        pair = sql[index : index + 2]

        if in_line_comment:
            if char == "\n":
                in_line_comment = False
            current.append(char)
        elif in_block_comment:
            current.append(char)
            if pair == "*/":
                current.append(sql[index + 1])
                index += 1
                in_block_comment = False
        elif in_string:
            current.append(char)
            if char == "'":
                if pair == "''":  # SQL escapes a quote by doubling it
                    current.append(sql[index + 1])
                    index += 1
                else:
                    in_string = False
        elif pair == "--":
            in_line_comment = True
            current.append(char)
        elif pair == "/*":
            in_block_comment = True
            current.append(char)
        elif char == "'":
            in_string = True
            current.append(char)
        elif char == ";":
            statements.append("".join(current))
            current = []
        else:
            current.append(char)
        index += 1

    statements.append("".join(current))
    return [stripped for statement in statements if (stripped := statement.strip())]


def connect(db_path: Path | str | None = None, *, busy_timeout_ms: int | None = None) -> sqlite3.Connection:
    """Open the metadata database with the invariants AQRL depends on.

    `isolation_level=None` disables the driver's implicit transaction
    management so `transaction()` below is the single, explicit place where
    commit boundaries are decided.

    Stage 4 (Implementation_Plan §6) is the first time two processes write
    this database at once — the scheduler and its dispatched worker
    subprocesses. Two pragmas make that survivable: **WAL** lets readers and
    the single writer proceed without blocking each other, and
    **`busy_timeout`** makes a writer that loses the race retry for a bounded
    window instead of failing immediately with `SQLITE_BUSY`. Both are
    connection-time pragmas, not schema, so the eventual PostgreSQL swap
    (TRD §3.2) is unaffected.
    """
    if db_path is None or busy_timeout_ms is None:
        from ..config import get_settings

        settings = get_settings()
        if db_path is None:
            db_path = settings.db_path
        if busy_timeout_ms is None:
            busy_timeout_ms = settings.busy_timeout_ms

    path = Path(db_path)
    if path.parent and not path.parent.exists():
        path.parent.mkdir(parents=True, exist_ok=True)

    conn = sqlite3.connect(path, isolation_level=None)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")  # Backend-Schema §0: FKs are enforced
    conn.execute("PRAGMA journal_mode = WAL")
    conn.execute(f"PRAGMA busy_timeout = {int(busy_timeout_ms)}")
    return conn


@contextmanager
def transaction(conn: sqlite3.Connection, *, immediate: bool = False) -> Iterator[sqlite3.Connection]:
    """Explicit transaction. Commits on success, rolls back on any exception.

    `immediate=True` issues `BEGIN IMMEDIATE`, taking the write lock up front
    instead of the default deferred `BEGIN`, which only upgrades to a write
    lock on the first write *inside* the transaction. Under concurrent
    writers, a deferred `BEGIN` lets two connections both start read-only and
    then race for the write lock mid-transaction — the classic SQLite
    "database is locked" deadlock. Every claim/complete path in the job queue
    (`aqrl/db/repositories/jobs.py`) uses `immediate=True` for exactly this
    reason.
    """
    conn.execute("BEGIN IMMEDIATE" if immediate else "BEGIN")
    try:
        yield conn
    except BaseException:
        conn.execute("ROLLBACK")
        raise
    conn.execute("COMMIT")
